[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
challenge_slashing = "DqQjh7bT9sri2fnZqh58nEpzeJb7jZaCNzb4CMGNqbEP"
stream_registry = "HCm2Bk65hCaevrs4N3oYegMBZBTPpzjoMB44JgTrTVSA"
subscription_royalty = "BMDH241mpXx3WHuRjWp7DpBrjmKSBYhttBgnFZd5aHYE"

[programs.localnet]
challenge_slashing = "DqQjh7bT9sri2fnZqh58nEpzeJb7jZaCNzb4CMGNqbEP"
stream_registry = "5mDTkhRWcqVi4YNBqLudwMTC4imfHjuCtRu82mmDpSRi"
subscription_royalty = "BMDH241mpXx3WHuRjWp7DpBrjmKSBYhttBgnFZd5aHYE"

[programs.testnet]
challenge_slashing = "DqQjh7bT9sri2fnZqh58nEpzeJb7jZaCNzb4CMGNqbEP"
stream_registry = "5mDTkhRWcqVi4YNBqLudwMTC4imfHjuCtRu82mmDpSRi"
subscription_royalty = "BMDH241mpXx3WHuRjWp7DpBrjmKSBYhttBgnFZd5aHYE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = ".keys/devnet.json"
